version: "3.9"

services:   
  rabbitmq: # login guest:guest
    image: rabbitmq:3-management
    hostname: "rabbitmq"
    ports:
    - "5672:5672"
    - "15672:15672"


  user_api:
    ports:
      - "5000:80"
      - "5001:443"
    image: retur/user_api
    build:
      context: ./UserAPI
      dockerfile: Dockerfile
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings:sqlConnection="Data Source=host.docker.internal\\SQLExpress, 1433; database=SocialNetworkUserDb; User ID=sa;Password=root;MultipleActiveResultSets=true;"
    restart: on-failure


  post_api:
    ports:
      - "5050:80"
      - "5051:443"
    image: retur/post_api
    build:
      context: ./PostAPI
      dockerfile: Dockerfile
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings:sqlConnection="Data Source=host.docker.internal\\SQLExpress, 1433; database=SocialNetworkPostDb; User ID=sa;Password=root;MultipleActiveResultSets=true;"
    restart: on-failure


  chat_api:
    ports:
      - "8080:80"
      - "8081:443"
    image: retur/chat_api
    build:
      context: ./ChatAPI
      dockerfile: Dockerfile
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings:sqlConnection="Data Source=host.docker.internal\\SQLExpress, 1433; database=SocialNetworkChatDb; User ID=sa;Password=root;MultipleActiveResultSets=true;"
    restart: on-failure


  authorization_api:
    ports:
      - "9001:443"
    image: retur/authorization_api
    build:
      context: ./AuthorizationAPI
      dockerfile: Dockerfile
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
    environment:
      - ASPNETCORE_URLS=https://+:443
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings:sqlConnection=Data Source=host.docker.internal\SQLExpress, 1433; database=SocialNetworkUserDb; User ID=sa;Password=root;MultipleActiveResultSets=true;
    restart: on-failure

