apiVersion: apps/v1
kind: Deployment
metadata:
  name: chat-api-deployment
  labels:
    app: chat-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: chat-api
  template:
    metadata:
      labels:
        app: chat-api
    spec:
      containers:
      - name: chat-api
        image: retur/chat_api:latest
        ports:
        - containerPort: 80
        - containerPort: 443
        env:
        - name: ConnectionStrings__sqlConnection
          value: "Data Source=host.docker.internal\\SQLExpress, 1433; database=SocialNetworkChatDb; User ID=sa;Password=root;MultipleActiveResultSets=true;"

---
apiVersion: v1
kind: Service
metadata:
  name: chat-api-service
spec:
  type: NodePort
  selector:
    app: chat-api
  ports:
    - protocol: TCP
      name: "82"
      port: 82
      targetPort: 80
      nodePort: 30082
    - protocol: TCP
      name: "445"
      port: 445
      targetPort: 445
      nodePort: 30445