apiVersion: apps/v1
kind: Deployment
metadata:
  name: post-api-deployment
  labels:
    app: post-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: post-api
  template:
    metadata:
      labels:
        app: post-api
    spec:
      containers:
      - name: post-api
        image: retur/post_api:latest
        ports:
        - containerPort: 80
        env:
        - name: ConnectionStrings__sqlConnection
          value: "Data Source=host.docker.internal\\SQLExpress, 1433; database=SocialNetworkPostDb; User ID=sa;Password=root;MultipleActiveResultSets=true;"
        - name: Authority__AuthorityURL
          value: "http://host.docker.internal:30901"
        - name: SenderRabbitMq__Hostname
          value: "host.docker.internal"
        - name: RecieverRabbitMq__Hostname
          value: "host.docker.internal"
---
apiVersion: v1
kind: Service
metadata:
  name: post-api-service
spec:
  type: NodePort
  selector:
    app: post-api
  ports:
    - protocol: TCP
      name: "80"
      port: 80
      targetPort: 80
      nodePort: 30080