apiVersion: v1
kind: Secret
metadata:
  name: database-secret
type: Opaque
data:
  postDatabaseConnection: IkRhdGEgU291cmNlPWhvc3QuZG9ja2VyLmludGVybmFsXFxTUUxFeHByZXNzLCAxNDMzOyBkYXRhYmFzZT1Tb2NpYWxOZXR3b3JrUG9zdERiOyBVc2VyIElEPXNhO1Bhc3N3b3JkPXJvb3Q7TXVsdGlwbGVBY3RpdmVSZXN1bHRTZXRzPXRydWU7Ig==
  chatDatabaseConnection: IkRhdGEgU291cmNlPWhvc3QuZG9ja2VyLmludGVybmFsXFxTUUxFeHByZXNzLCAxNDMzOyBkYXRhYmFzZT1Tb2NpYWxOZXR3b3JrQ2hhdERiOyBVc2VyIElEPXNhO1Bhc3N3b3JkPXJvb3Q7TXVsdGlwbGVBY3RpdmVSZXN1bHRTZXRzPXRydWU7Ig==
  userDatabaseConnection: RGF0YSBTb3VyY2U9aG9zdC5kb2NrZXIuaW50ZXJuYWxcU1FMRXhwcmVzcywgMTQzMzsgZGF0YWJhc2U9U29jaWFsTmV0d29ya1VzZXJEYjsgVXNlciBJRD1zYTtQYXNzd29yZD1yb290O011bHRpcGxlQWN0aXZlUmVzdWx0U2V0cz10cnVlOw==
  AuthorizationDatabaseConnection: RGF0YSBTb3VyY2U9aG9zdC5kb2NrZXIuaW50ZXJuYWxcU1FMRXhwcmVzcywgMTQzMzsgZGF0YWJhc2U9U29jaWFsTmV0d29ya1VzZXJEYjsgVXNlciBJRD1zYTtQYXNzd29yZD1yb290O011bHRpcGxlQWN0aXZlUmVzdWx0U2V0cz10cnVlOw==