apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-api-deployment
  labels:
    app: user-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: user-api
  template:
    metadata:
      labels:
        app: user-api
    spec:
      containers:
      - name: user-api
        image: retur/user_api:latest
        ports:
        - containerPort: 80
        - containerPort: 443
        env:
        - name: ConnectionStrings__sqlConnection
          value: "Data Source=host.docker.internal\\SQLExpress, 1433; database=SocialNetworkUserDb; User ID=sa;Password=root;MultipleActiveResultSets=true;"

---
apiVersion: v1
kind: Service
metadata:
  name: user-api-service
spec:
  type: NodePort
  selector:
    app: user-api
  ports:
    - protocol: TCP
      name: "81"
      port: 81
      targetPort: 80
      nodePort: 30081
    - protocol: TCP
      name: "444"
      port: 444
      targetPort: 443
      nodePort: 30444