apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-api-deployment
  labels:
    app: user-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-api
  template:
    metadata:
      labels:
        app: user-api
    spec:
      containers:
      - name: user-api
        image: retur/user_api:latest
        ports:
        - containerPort: 80
        env:
        - name: ConnectionStrings__sqlConnection
          value: "Data Source=host.docker.internal\\SQLExpress, 1433; database=SocialNetworkUserDb; User ID=sa;Password=root;MultipleActiveResultSets=true;"
        - name: Authority__AuthorityURL
          value: "http://host.docker.internal:30901"
        - name: SenderRabbitMq__Hostname
          value: "host.docker.internal"
        - name: RecieverRabbitMq__Hostname
          value: "host.docker.internal"

---
apiVersion: v1
kind: Service
metadata:
  name: user-api-service
spec:
  type: ClusterIP
  selector:
    app: user-api
  ports:
    - protocol: TCP
      port: 81
      targetPort: 80